### ISSUE TITLE
Payload gets random characters at the tail

### ISSUE THREAD

**Issue by zhouyuchong** [teknoir/deepstream-mqtt-sink#2]
Greetings again.
Thanks to your help, the mqtt protocol adaptor almost works.
However, there is a little problem. The message seems get some strange random characters at the end like [this](https://drive.google.com/file/d/199aGyh9Qqjvyv92S9Ly3fFpiRWHdr5K-/view?usp=sharing). As you can see, there are some random chars after the `videopath' sometimes.  While this is not a big problem cause I can filter the data, I still try to figure out why.
1. First I checked the payload generate by `nvmsgconv`. I output the payload in `nvds_msg2p_generate` and it's 100% correct.
2. Then I checked the codes in your repo, I tried to output the payload at `nvds_msgapi_send_async` in `libnvds_mqtt_sin.cpp`, and the payload is differ from it in `nvmsgconv`. So that's the problem.
3. I send the same message using official kafka adaptor, and it's correct.
As the nvmsgbroker is not open-source, now I don't know how to continue this work.
Do you have any ideas? Please let me know, appreciate your advice.

**Comment by tekn0ir** [comment]
Hi, you are correct, there are some random chars at the end. I assumed it came from `nvmsgconv`, but I have not had time to dig into it. I just filtered it out, on the receiving end, like you said.

Do I understand you correct, that you think it comes from `nvmsgbroker`? Or does my code produce something it should not?

I think I have the code for `nvmsgbroker` but I am unsure how I can share it with you?
I found the code in a docker image they have:
`docker run -ti --rm --name=ds_source nvcr.io/nvidia/deepstream:6.0.1-devel bash`
You can find the source under: /opt/nvidia/deepstream/deepstream-6.0/sources/gst-plugins/gst-nvmsgbroker
So in another terminal window you can copy source from the running container like this:
`docker cp ds_source:/opt/nvidia/deepstream/deepstream-6.0/sources /to/a/local/path`

**Comment by zhouyuchong** [comment]
got it, I'll check the source code later :)

**Comment by zhouyuchong** [comment]
> 

Hi, finally solve the problem. As you said, IT IS caused by `nvmsgconv`, this may be a deepstream bug: 

in the function `nds_msg2p_generate` from `/opt/nvidia/deepstream/deepstream/sources/libs/nvmsgconv/nvmsgconv.cpp`, they get the length of message by `strlen`, and in function `nds_msg2p_generate`, there is an annotation:
```
Remove '\0' character at the end of string and just copy the content
```
That's the problem, c/c++ use '\0' to get the end of a string. I guess these random characters are because of this reason. 

So I use `len+1` instead of `len` when use `g_memdup()` to copy message to payload. And it worked.

Hope this works for you too. :)

**Comment by tekn0ir** [comment]
Thanks a lot! 
Great detective work. Lets keep this issue open to let others know that this is an issue!

I was to lazy(or maybe too busy :-P) to do it. I was already so disappointed at what Deepstream actually is and the NVIDIA bloatware in general. The maturity level of Deepstream 6.0 I would say is still in a Demo/Beta stage.

The JSON format from `nvdsinfer` is abysmal, having label/class as a key and using pixels instead of a percentage format (0.0-1.0) for object bbox. Its a mess if you want to build something that is versatile and configurable on top of it.

I receive the messages in a Javascript application. I think your solution is better, but here is how I did it:
```javascript
// First remove crap from end of string
let compensateForNVIDACrap = (str) => {
    let stack = [];

    let open = {
        '{': '}',
        '[': ']',
        '(': ')'
    };

    let closed = {
        '}': true,
        ']': true,
        ')': true
    }

    for (let i = 0; i < str.length; i++) {

        let char = str[i];

        if (open[char]) {
            stack.push(char);
        } else if (closed[char]) {
            if (open[stack.pop()] !== char) return false;
            if (stack.length === 0) {
                return str.substr(0, i+1);
            }
        }
    }
    return false;
}

let payload = JSON.parse(compensateForNVIDACrap(msg.payload));
```

**Comment by zhouyuchong** [comment]
Hi there! 
I spent some spare time to dig into this and finally i found the root. first of all, the `nvmsbconv` cut off the '\0' of the message, so the payload is a buffer without '\0'. then the buffer goes to `nvmsgbroker`, the mqtt/kafka should decode this payload and send it out. at this point, we should specify the length of this payload, if not, the mqtt will find until meet a '\0'.

so the solution is quite simple, tell the broker the length of the payload at the decode stage.

**Comment by tekn0ir** [comment]
Awesome work! Thank you so much! I merged your Pull Request!

Are you a student or do you work for someone? Ping me, if you some day need a new job! ;-)

**Comment by tekn0ir** [comment]
I close this issue now when it is solved.
